**Cell 1: Setup đường dẫn và Import thư viện**


In [ ]:
import numpy as np
from part1_skeleton import Matrix
from gauss import verify_solution
from scipy.linalg import null_space

**Cell 2: Test Gaussian Elimination**

In [ ]:
# Case 1: Normal
A = Matrix([
    [0, 2, 1],
    [1, -2, -3],
    [-1, 1, 2]
])
b = [-8, 0, 3]

result = A.gaussian_eliminate(b)
A_bar, x, count = result
print("NGHIỆM CỦA HỆ PHƯƠNG TRÌNH:", x)
verify_solution(A.data, x, b)


# Case 2: Pivot = 0 (Vô nghiệm)
A = Matrix([
    [1, 0, 0],
    [0, 0, 3],
    [0, 0, 1],
])
b = [3, 15, 14]

result = A.gaussian_eliminate(b)
A_bar, x, count = result
print("NGHIỆM CỦA HỆ PHƯƠNG TRÌNH:", x)
verify_solution(A.data, x, b)

NGHIỆM CỦA HỆ PHƯƠNG TRÌNH: [-4.0, -5.0, 2.0]
Solution is true

NGHIỆM CỦA HỆ PHƯƠNG TRÌNH: None
Solution is true



**Cell 3: Test Determinant**

In [ ]:
A = Matrix([
    [0, 2, 1],
    [1, -2, -3],
    [-1, 1, 2]
])
custom_det = A.det()

print("--- KẾT QUẢ CUSTOM ---")
print(f'Định thức của ma trận A: {custom_det}')

print("\n--- KIỂM CHỨNG VỚI NUMPY ---")
np_det = np.linalg.det(np.array(A.data))
print(f'Định thức của ma trận A (NumPy): {np_det:.4f}')

--- KẾT QUẢ CUSTOM ---
Định thức của ma trận A: 1.0

--- KIỂM CHỨNG VỚI NUMPY ---
Định thức của ma trận A (NumPy): 1.0000


**Cell 4: Test Inverse**

In [8]:
m2 = Matrix([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])
r2 = m2.inverse()

print("--- KẾT QUẢ CUSTOM ---")
print("Ma trận nghịch đảo A^-1:")
r2_list = r2.data if hasattr(r2, 'data') else r2
for row in r2_list:
    print(row)

print("\n--- KIỂM THỬ A * A^-1 = I ---")
np_m2 = np.array(m2.data)
np_r2 = np.array(r2_list)
I_check = np.dot(np_m2, np_r2)
print("Kết quả A * A^-1 (Làm tròn):")
print(np.round(I_check, 0))

print("\n--- KIỂM CHỨNG VỚI NUMPY ---")
np_inv = np.linalg.inv(np_m2)
print("Ma trận nghịch đảo A^-1 (NumPy):")
print(np_inv)

--- KẾT QUẢ CUSTOM ---
Ma trận nghịch đảo A^-1:
[-24.00000000000009, 18.000000000000068, 5.000000000000018]
[20.00000000000007, -15.000000000000053, -4.000000000000014]
[-5.000000000000018, 4.000000000000013, 1.0000000000000036]

--- KIỂM THỬ A * A^-1 = I ---
Kết quả A * A^-1 (Làm tròn):
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]

--- KIỂM CHỨNG VỚI NUMPY ---
Ma trận nghịch đảo A^-1 (NumPy):
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


**Cell 5: Test Rank and Basis**

In [10]:

print("========== TEST RANK AND BASIS ==========\n")

mat = Matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---")

custom_result = mat.rank_and_basis()
print(custom_result) 


print("\n--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---")
np_A = np.array(A.data)

np_rank = np.linalg.matrix_rank(np_A)
print(f"1. Hạng của ma trận (NumPy): {np_rank}")
print(f"2. Chiều của Không gian cột dim(C(A)): {np_rank}")
print(f"3. Chiều của Không gian dòng dim(R(A)): {np_rank}")
ns = null_space(np_A)
print(f"4. Cơ sở của Không gian nghiệm (SciPy null_space):")
if ns.size > 0:
    print(np.round(ns, 4))
else:
    print("Không gian nghiệm chỉ chứa vector 0 (Trivial null space)")

========== TEST RANK AND BASIS ==========

--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---
(2, ([(1.00, 4.00, 7.00)^T, (2.00, 5.00, 8.00)^T], [(1.00, 0.00, -1.00), (0.00, 1.00, 2.00)], [(1.00, -2.00, 1.00)^T]))

--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---
1. Hạng của ma trận (NumPy): 3
2. Chiều của Không gian cột dim(C(A)): 3
3. Chiều của Không gian dòng dim(R(A)): 3
4. Cơ sở của Không gian nghiệm (SciPy null_space):
Không gian nghiệm chỉ chứa vector 0 (Trivial null space)
