**Cell 1: Setup đường dẫn và Import thư viện**


In [47]:
import sys
import os
import numpy as np
from scipy.linalg import null_space

root_path = os.path.abspath(os.path.join(os.getcwd(), ".."))
if root_path not in sys.path:
    sys.path.insert(0, root_path)

from part1.part1_skeleton import Matrix
from part1.gauss import verify_solution

**Cell 2: Test Gaussian Elimination**

In [48]:
# --- DỮ LIỆU KIỂM THỬ (TEST CASES) ---
test_data = [
    {
        "A": [[0, 2, 1], [1, -2, -3], [-1, 1, 2]],
        "b": [-8, 0, 3],
        "desc": "Case 1: Normal (Swap row)"
    },
    {
        "A": [[1, 0, 0], [0, 0, 3], [0, 0, 1]],
        "b": [3, 15, 14],
        "desc": "Case 2: Pivot = 0 (No Solution)"
    },
    {
        "A": [[1, 1, 1], [0, 2, -1], [1, 3, 0]],
        "b": [6, 3, 9],
        "desc": "Case 3: Infinitely Many Solutions"
    },
    {
        "A": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "b": [5, -2, 10],
        "desc": "Case 4: Identity Matrix"
    },
    {
        "A": [[2, 4, -2], [0, 1, 1], [0, 0, 4]],
        "b": [2, 4, 8],
        "desc": "Case 5: Upper Triangular"
    }
]

# --- CHẠY KIỂM THỬ ---
for i, test in enumerate(test_data):
    print(f"--- {test['desc']} ---") 
    
    A_obj = Matrix(test['A'])
    b_val = test['b']
    
    # Thực hiện khử Gauss
    result = A_obj.gaussian_eliminate(b_val)
    A_bar, x, count = result
    
    # In kết quả nghiệm
    print(f"NGHIỆM CỦA HỆ PHƯƠNG TRÌNH: {x}")
    
    if x is not None:
        verify_solution(test['A'], x, b_val)
    else:
        print("Solution is true")
    
    print() # Tạo dòng trống giữa các case cho dễ nhìn

--- Case 1: Normal (Swap row) ---
NGHIỆM CỦA HỆ PHƯƠNG TRÌNH: [-4.0, -5.0, 2.0]
Solution is true


--- Case 2: Pivot = 0 (No Solution) ---
NGHIỆM CỦA HỆ PHƯƠNG TRÌNH: None
Solution is true

--- Case 3: Infinitely Many Solutions ---
NGHIỆM CỦA HỆ PHƯƠNG TRÌNH: None
Solution is true

--- Case 4: Identity Matrix ---
NGHIỆM CỦA HỆ PHƯƠNG TRÌNH: [5.0, -2.0, 10.0]
Solution is true


--- Case 5: Upper Triangular ---
NGHIỆM CỦA HỆ PHƯƠNG TRÌNH: [-1.0, 2.0, 2.0]
Solution is true




**Cell 3: Test Determinant**

In [50]:
test_det_data_part1 = [
    {"A": [[0, 2, 1], [1, -2, -3], [-1, 1, 2]]}, # Case 1: Swap row
    {"A": [[1, 2, 3], [2, 4, 6], [7, 8, 9]]},    # Case 2: Det = 0
    {"A": [[1, 0, 0], [0, 1, 0], [0, 0, 1]]},    # Case 3: Identity
    {"A": [[2, 0, 0], [0, 5, 0], [0, 4, 3]]}     # Case 4: Triangular
]

for test in test_det_data_part1:
    A_obj = Matrix(test["A"])
    custom_det = float(A_obj.det()) + 0.0
    
    print("--- KẾT QUẢ CUSTOM ---")
    print(f'Định thức của ma trận A: {custom_det:.4f}')

    print("\n--- KIỂM CHỨNG VỚI NUMPY ---")
    np_det = np.linalg.det(np.array(A_obj.data)) + 0.0
    print(f'Định thức của ma trận A (NumPy): {np_det:.4f}\n')

--- KẾT QUẢ CUSTOM ---
Định thức của ma trận A: 1.0000

--- KIỂM CHỨNG VỚI NUMPY ---
Định thức của ma trận A (NumPy): 1.0000

--- KẾT QUẢ CUSTOM ---
Định thức của ma trận A: 0.0000

--- KIỂM CHỨNG VỚI NUMPY ---
Định thức của ma trận A (NumPy): 0.0000

--- KẾT QUẢ CUSTOM ---
Định thức của ma trận A: 1.0000

--- KIỂM CHỨNG VỚI NUMPY ---
Định thức của ma trận A (NumPy): 1.0000

--- KẾT QUẢ CUSTOM ---
Định thức của ma trận A: 30.0000

--- KIỂM CHỨNG VỚI NUMPY ---
Định thức của ma trận A (NumPy): 30.0000



In [51]:
# Chạy riêng case này vì output trước đó quá dài
test_case_5 = {"A": [[4, 0, 0], [0, 3, 0], [0, 0, 2]]} # Case 5: Diagonal (4*3*2 = 24.0)

A_obj = Matrix(test_case_5["A"])
custom_det = float(A_obj.det()) + 0.0

print("--- KẾT QUẢ CUSTOM (CASE 5) ---")
print(f'Định thức của ma trận A: {custom_det:.4f}')

print("\n--- KIỂM CHỨNG VỚI NUMPY ---")
np_det = np.linalg.det(np.array(A_obj.data)) + 0.0
print(f'Định thức của ma trận A (NumPy): {np_det:.4f}')

--- KẾT QUẢ CUSTOM (CASE 5) ---
Định thức của ma trận A: 24.0000

--- KIỂM CHỨNG VỚI NUMPY ---
Định thức của ma trận A (NumPy): 24.0000


**Cell 4: Test Inverse**

In [53]:
test_inv_1_2 = [
    {"A": [[1, 2, 3], [0, 1, 4], [5, 6, 0]]},
    {"A": [[1, 0, 0], [0, 1, 0], [0, 0, 1]]}
]

for test in test_inv_1_2:
    m = Matrix(test["A"])
    r = m.inverse()
    r_list = r.data if hasattr(r, 'data') else r
    
    print("--- KẾT QUẢ CUSTOM ---")
    for row in r_list:
        print([round(val, 4) for val in row])

    print("\n--- KIỂM THỬ A * A^-1 = I ---")
    print(np.round(np.dot(np.array(m.data), np.array(r_list)), 0) + 0.0)
    print("-" * 30)

--- KẾT QUẢ CUSTOM ---
[-24.0, 18.0, 5.0]
[20.0, -15.0, -4.0]
[-5.0, 4.0, 1.0]

--- KIỂM THỬ A * A^-1 = I ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
------------------------------
--- KẾT QUẢ CUSTOM ---
[1.0, 0.0, 0.0]
[0.0, 1.0, 0.0]
[0.0, 0.0, 1.0]

--- KIỂM THỬ A * A^-1 = I ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
------------------------------


In [56]:
test_inv_3_4 = [
    {"A": [[2, 5], [1, 3]]},
    {"A": [[1, 2, 0], [0, 1, 3], [0, 0, 1]]}
]

for test in test_inv_3_4:
    m = Matrix(test["A"])
    r = m.inverse()
    r_list = r.data if hasattr(r, 'data') else r
    
    print("--- KẾT QUẢ CUSTOM ---")
    for row in r_list:
        print([round(val, 4) for val in row])

    print("\n--- KIỂM THỬ A * A^-1 = I ---")
    print(np.round(np.dot(np.array(m.data), np.array(r_list)), 0) + 0.0)
    print("-" * 30)

--- KẾT QUẢ CUSTOM ---
[3.0, -5.0]
[-1.0, 2.0]

--- KIỂM THỬ A * A^-1 = I ---
[[1. 0.]
 [0. 1.]]
------------------------------
--- KẾT QUẢ CUSTOM ---
[1.0, -2.0, 6.0]
[0.0, 1.0, -3.0]
[0.0, 0.0, 1.0]

--- KIỂM THỬ A * A^-1 = I ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
------------------------------


In [55]:
test_inv_5 = {"A": [[4, 0, 0], [0, 2, 0], [0, 0, 5]]}

m = Matrix(test_inv_5["A"])
r = m.inverse()
r_list = r.data if hasattr(r, 'data') else r

print("--- KẾT QUẢ CUSTOM (CASE 5) ---")
for row in r_list:
    print([round(val, 4) for val in row])

print("\n--- KIỂM THỬ A * A^-1 = I ---")
print(np.round(np.dot(np.array(m.data), np.array(r_list)), 0) + 0.0)

--- KẾT QUẢ CUSTOM (CASE 5) ---
[0.25, 0.0, 0.0]
[0.0, 0.5, 0.0]
[0.0, 0.0, 0.2]

--- KIỂM THỬ A * A^-1 = I ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Cell 5: Test Rank and Basis**

In [10]:

print("========== TEST RANK AND BASIS ==========\n")

mat = Matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---")

custom_result = mat.rank_and_basis()
print(custom_result) 


print("\n--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---")
np_A = np.array(A.data)

np_rank = np.linalg.matrix_rank(np_A)
print(f"1. Hạng của ma trận (NumPy): {np_rank}")
print(f"2. Chiều của Không gian cột dim(C(A)): {np_rank}")
print(f"3. Chiều của Không gian dòng dim(R(A)): {np_rank}")
ns = null_space(np_A)
print(f"4. Cơ sở của Không gian nghiệm (SciPy null_space):")
if ns.size > 0:
    print(np.round(ns, 4))
else:
    print("Không gian nghiệm chỉ chứa vector 0 (Trivial null space)")

========== TEST RANK AND BASIS ==========

--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---
(2, ([(1.00, 4.00, 7.00)^T, (2.00, 5.00, 8.00)^T], [(1.00, 0.00, -1.00), (0.00, 1.00, 2.00)], [(1.00, -2.00, 1.00)^T]))

--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---
1. Hạng của ma trận (NumPy): 3
2. Chiều của Không gian cột dim(C(A)): 3
3. Chiều của Không gian dòng dim(R(A)): 3
4. Cơ sở của Không gian nghiệm (SciPy null_space):
Không gian nghiệm chỉ chứa vector 0 (Trivial null space)


In [59]:
mat = Matrix([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

print("--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---")
custom_result = mat.rank_and_basis()
print(custom_result) 

print("\n--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---")
np_A = np.array(mat.data)
np_rank = np.linalg.matrix_rank(np_A)
print(f"1. Hạng của ma trận (NumPy): {np_rank}")
print(f"2. Chiều của Không gian cột dim(C(A)): {np_rank}")
print(f"3. Chiều của Không gian dòng dim(R(A)): {np_rank}")
ns = null_space(np_A)
print(f"4. Cơ sở của Không gian nghiệm (SciPy null_space):")
if ns.size > 0:
    print(np.round(ns, 4))
else:
    print("Không gian nghiệm chỉ chứa vector 0 (Trivial null space)")

--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---
(3, ([(1.00, 0.00, 0.00)^T, (0.00, 1.00, 0.00)^T, (0.00, 0.00, 1.00)^T], [(1.00, 0.00, 0.00), (0.00, 1.00, 0.00), (0.00, 0.00, 1.00)], []))

--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---
1. Hạng của ma trận (NumPy): 3
2. Chiều của Không gian cột dim(C(A)): 3
3. Chiều của Không gian dòng dim(R(A)): 3
4. Cơ sở của Không gian nghiệm (SciPy null_space):
Không gian nghiệm chỉ chứa vector 0 (Trivial null space)


In [60]:
mat = Matrix([
    [1, 2, 3],
    [0, 0, 0],
    [1, 2, 3]
])

print("--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---")
custom_result = mat.rank_and_basis()
print(custom_result) 

print("\n--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---")
np_A = np.array(mat.data)
np_rank = np.linalg.matrix_rank(np_A)
print(f"1. Hạng của ma trận (NumPy): {np_rank}")
print(f"2. Chiều của Không gian cột dim(C(A)): {np_rank}")
print(f"3. Chiều của Không gian dòng dim(R(A)): {np_rank}")
ns = null_space(np_A)
print(f"4. Cơ sở của Không gian nghiệm (SciPy null_space):")
if ns.size > 0:
    print(np.round(ns, 4))
else:
    print("Không gian nghiệm chỉ chứa vector 0 (Trivial null space)")

--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---
(1, ([(1.00, 0.00, 1.00)^T], [(1.00, 2.00, 3.00)], [(-3.00, 0.00, 1.00)^T, (-2.00, 1.00, 0.00)^T]))

--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---
1. Hạng của ma trận (NumPy): 1
2. Chiều của Không gian cột dim(C(A)): 1
3. Chiều của Không gian dòng dim(R(A)): 1
4. Cơ sở của Không gian nghiệm (SciPy null_space):
[[-0.9636  0.    ]
 [ 0.1482 -0.8321]
 [ 0.2224  0.5547]]


In [61]:
mat = Matrix([
    [1, 0, 2],
    [0, 1, 3]
])

print("--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---")
custom_result = mat.rank_and_basis()
print(custom_result) 

print("\n--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---")
np_A = np.array(mat.data)
np_rank = np.linalg.matrix_rank(np_A)
print(f"1. Hạng của ma trận (NumPy): {np_rank}")
print(f"2. Chiều của Không gian cột dim(C(A)): {np_rank}")
print(f"3. Chiều của Không gian dòng dim(R(A)): {np_rank}")
ns = null_space(np_A)
print(f"4. Cơ sở của Không gian nghiệm (SciPy null_space):")
if ns.size > 0:
    print(np.round(ns, 4))
else:
    print("Không gian nghiệm chỉ chứa vector 0 (Trivial null space)")

--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---
(2, ([(1.00, 0.00)^T, (0.00, 1.00)^T], [(1.00, 0.00, 2.00), (0.00, 1.00, 3.00)], [(-2.00, -3.00, 1.00)^T]))

--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---
1. Hạng của ma trận (NumPy): 2
2. Chiều của Không gian cột dim(C(A)): 2
3. Chiều của Không gian dòng dim(R(A)): 2
4. Cơ sở của Không gian nghiệm (SciPy null_space):
[[-0.5345]
 [-0.8018]
 [ 0.2673]]


In [62]:
mat = Matrix([
    [1, 0, 2],
    [0, 1, 3],
    [1, 1, 5]
])

print("--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---")
custom_result = mat.rank_and_basis()
print(custom_result) 

print("\n--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---")
np_A = np.array(mat.data)
np_rank = np.linalg.matrix_rank(np_A)
print(f"1. Hạng của ma trận (NumPy): {np_rank}")
print(f"2. Chiều của Không gian cột dim(C(A)): {np_rank}")
print(f"3. Chiều của Không gian dòng dim(R(A)): {np_rank}")
ns = null_space(np_A)
print(f"4. Cơ sở của Không gian nghiệm (SciPy null_space):")
if ns.size > 0:
    print(np.round(ns, 4))
else:
    print("Không gian nghiệm chỉ chứa vector 0 (Trivial null space)")

--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---
(2, ([(1.00, 0.00, 1.00)^T, (0.00, 1.00, 1.00)^T], [(1.00, 0.00, 2.00), (0.00, 1.00, 3.00)], [(-2.00, -3.00, 1.00)^T]))

--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---
1. Hạng của ma trận (NumPy): 2
2. Chiều của Không gian cột dim(C(A)): 2
3. Chiều của Không gian dòng dim(R(A)): 2
4. Cơ sở của Không gian nghiệm (SciPy null_space):
[[ 0.5345]
 [ 0.8018]
 [-0.2673]]


In [63]:
mat = Matrix([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])

print("--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---")
custom_result = mat.rank_and_basis()
print(custom_result) 

print("\n--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---")
np_A = np.array(mat.data)
np_rank = np.linalg.matrix_rank(np_A)
print(f"1. Hạng của ma trận (NumPy): {np_rank}")
print(f"2. Chiều của Không gian cột dim(C(A)): {np_rank}")
print(f"3. Chiều của Không gian dòng dim(R(A)): {np_rank}")
ns = null_space(np_A)
print(f"4. Cơ sở của Không gian nghiệm (SciPy null_space):")
if ns.size > 0:
    print(np.round(ns, 4))
else:
    print("Không gian nghiệm chỉ chứa vector 0 (Trivial null space)")

--- KẾT QUẢ CUSTOM (HẠNG VÀ 3 KHÔNG GIAN CƠ SỞ) ---
(0, ([], [], [(0.00, 0.00, 1.00)^T, (0.00, 1.00, 0.00)^T, (1.00, 0.00, 0.00)^T]))

--- KIỂM CHỨNG VỚI NUMPY/SCIPY ---
1. Hạng của ma trận (NumPy): 0
2. Chiều của Không gian cột dim(C(A)): 0
3. Chiều của Không gian dòng dim(R(A)): 0
4. Cơ sở của Không gian nghiệm (SciPy null_space):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
